### ISSUE TITLE
doesn't have central european characters

### ISSUE THREAD

**Issue by pavelkouril** [theleagueof/raleway#1]
Hello!

I find your font beautiful, but it has one drawback -- it doesn't contain central european characters (ie. ř, ť, č, ů, ě, ď).
Would it be possible to add them?

Thanks in advance
pajousek

**Comment by alerque** [comment]
In case you are still interested in this, the [latest release](https://github.com/theleagueof/raleway/releases/latest) looks like this:

![image](https://user-images.githubusercontent.com/173595/91451129-c6b0ee80-e885-11ea-9e14-8a6e138535a9.png)

Of course many more glyphs are covered too, but I think that covers the ones you asked about.
