### ISSUE TITLE
Error on font validation (Mac OS X)

### ISSUE THREAD

**Issue by jaredhowland** [theleagueof/raleway#11]
I get the following warning when validating the font on Mac OS X (10.11.3) during attempted install using Font Book (default OS X app for font management):

'name' table structure

**Comment by edrozenberg** [comment]
Same issue. Can probably be fixed with Glyphs or Glyphs mini apps but those require purchase.

**Comment by alerque** [comment]
I believe this issue has been fixed in some versions of the font out there, but those fixes have not been merged back to this repository properly. We're working on making that happen.

**Comment by alerque** [comment]
Many many many advancements to this font family have been merged from other forks. I believe as of the current release this should be a non-issue. Please feel welcome to report any issues you do have!
