### ISSUE TITLE
Hello, this no work for spanish language á,é,í,ó,ú

### ISSUE THREAD

**Issue by jofret** [theleagueof/raleway#12]
Hello this fonts are very pretty but no work for spanish language: á,é,í,ó,ú, etc

**Comment by alerque** [comment]
In case you are still interested, the [latest release](https://github.com/theleagueof/raleway/releases/latest) of this font looks like this for the characters you mention:

![image](https://user-images.githubusercontent.com/173595/91451965-adf50880-e886-11ea-8258-9cdccec7e664.png)

Of course there are more, but I'm pretty sure Spanish is covered.
