### ISSUE TITLE
Add letter: Ä and ä 

### ISSUE THREAD

**Issue by DavidLundell** [theleagueof/raleway#13]
Hello! Love this font, good job! However the font is missing this letter: **Ä** and **ä**. 
Would be awsome if you could add it in the future. It's mainly used in Sweden and Finland, but I read it's also used in German, Estonian and Slovakian alphabet to name a few.

**Comment by alerque** [comment]
In case your are still interested, the 4.100 release of the font looks like this:

![image](https://user-images.githubusercontent.com/173595/91450380-e85da600-e884-11ea-8600-4f19b3bdcf82.png)
