### ISSUE TITLE
Update to the full family

### ISSUE THREAD

**Issue by davelab6** [theleagueof/raleway#2]
Please integrate http://www.impallari.com/projects/overview/matt-mcinerneys-raleway-family :)

**Comment by alerque** [comment]
This font family has had 18 styles released for the last 8 years. Not having this repo up to date is a shame. @theleagueof please see my email offering to help with repositories!

**Comment by alerque** [comment]
It took a long time, but after my own complaint about this issue above the League *finally* let me help! And this is now done. Furthermore the even later updates from the [TypeNetwork/Raleway](https://github.com/TypeNetwork/Raleway) project (which was forked from [impallari/Raleway](https://github.com/impallari/Raleway)) have also been integrated here.
