### ISSUE TITLE
Where are the lining numerals?

### ISSUE THREAD

**Issue by dandv** [theleagueof/raleway#5]
The README says "It is a display face that features both old style and lining numerals".

I discovered [Raleway via Google Fonts](https://www.google.com/fonts/specimen/Raleway), but I can only see the old style fonts

![image](https://cloud.githubusercontent.com/assets/33569/2534884/01460562-b584-11e3-8a12-716f2afec18e.png)

**Comment by ianbytchek** [comment]
True… but being one of the most popular Google fonts with Safari [not supporting this](http://caniuse.com/#search=font-feature-settings) yet it's kind of a problem. Raleways absolutely kicks ass, but jumpy numerals as it seems isn't many's favourite feature. 

Wouldn't it be better to keep the old style as a customisable option and use aligned numerals by default? Things evolve, things get better, people who care about their typography won't have problems with a little maintenance if they really want to use the old style. Pretty sure of that.

**Comment by zkirill** [comment]
Raleway is an absolutely incredible piece of art but I really need to use lining numerals in the browser. The following doesn't seem to work.

```css
font-feature-settings: 'lnum';
-moz-font-feature-settings: 'lnum=1';
-ms-font-feature-settings: 'lnum';
-webkit-font-feature-settings: 'lnum';
-o-font-feature-settings: 'lnum';
```

**Comment by ianbytchek** [comment]
@zkirill the right way to make this work is to use `font-feature-settings: "lnum" 1;` with the right prefixes. But quite a few browsers are still ignoring this…

**Comment by zkirill** [comment]
@ianbytchek Thank you! Still can't get it to work. :smiley: Yes, the browser support table for `font-feature-settings` looks pretty grim.

**Comment by luisrudge** [comment]
any news on this? I can't do this work with chrome/safari :(

**Comment by ianbytchek** [comment]
It works alright in OS X in [Chrome](https://cloud.githubusercontent.com/assets/1086845/15348534/bb78ced0-1cdc-11e6-8aac-168f2bae3dd9.png) and [Safari](https://cloud.githubusercontent.com/assets/1086845/15348546/cec01ade-1cdc-11e6-97bd-f23db4b06a9f.png), but not in Windows the last time I checked.

**Comment by luisrudge** [comment]
oh, that sucks :( I love this font, but those misaligned numbers SUCK big time.

**Comment by cssobral2013** [comment]
Update: I made a version that has lining numerals by default, so I virtually solved this problem. Check out at: <https://github.com/cssobral2013/rising-sun> Cheers!

**Comment by h-ibaldo** [comment]
I also made a version of Raleway with lining numerals, and it's as easy to use as a Google Font: you can embed it to your website with a single line of code. Check it here:
https://github.com/h-ibaldo/Raleway_Fixed_Numerals

**Comment by atilkan** [comment]
A bug given as a feature.

**Comment by h-ibaldo** [comment]
Why would you call it a bug @atilkan? Text firgures are very useful. I believe the problem most people have with Raleway numerals is that, being it such a great display font, that works so well in uppercase titles, the text figures, designed to be used with lowercase text, look out of place, or unaligned: they're not, they have x height, ascenders  and descenders, just like the lowercase alphabet. Another problem I faced more than once is while using Raleway for pricing layouts. 

Anyway, the Rawline font was created to fix this:
https://h-ibaldo.github.io/Raleway_Fixed_Numerals/

**Comment by ethangromet** [comment]
Thank you Rawline!!!! :)

**Comment by atilkan** [comment]
@h-ibaldo As you said to, there is something to fix. I call it bug. You cal call it Santa Cruz.

**Comment by dandv** [comment]
It's a matter of style whether misaligned numerals are a bug or feature - see http://ux.stackexchange.com/questions/54740/what-is-the-appeal-of-old-style-numbers-and-why-do-modern-fonts-still-include-th

**Comment by ianbytchek** [comment]
The matter of style is what you chose to use. Default option is a matter of common sense. Quoting the most popular answer from that discussion:

> There are fonts that support both old style and modern numbers. These fonts can easily be used for title, paragraph, table and graph text.

Since we don't live in old times good sir, it feels more appropriate to have modern numbers as a default option – common sense. All that aside, every major browser including Safari already [supports](http://caniuse.com/#feat=font-feature) `font-feature`.

![image](https://cloud.githubusercontent.com/assets/1086845/20339230/998725cc-abf4-11e6-9d7d-728d865ca7e0.png)

![image](https://cloud.githubusercontent.com/assets/1086845/20339262/c141fec0-abf4-11e6-90d6-bfddc4a3c468.png)

![image](https://cloud.githubusercontent.com/assets/1086845/20339277/d409337a-abf4-11e6-8846-6bab221b4a6e.png)

**Comment by dandv** [comment]
I also hate the old style. That's why I asked that question on UX.SE and filed this issue. If I were a fonts dictator, I'd ban old style numerals, those ligatures that combine "f" with a following "i", fonts whose "l" looks indistinguishable from "I", "O" from "0" etc.

**Comment by ianbytchek** [comment]
@dandv if you were a font dictator I'd totally vote for you and pray on your barbarian regime and repressions against liberalistic ligature freedoms! :heart_eyes:

![image](https://cloud.githubusercontent.com/assets/1086845/20364675/6a840e84-ac5d-11e6-8208-74e4fee3f06b.png)

**Comment by stevenvachon** [comment]
This doesn't seem to have been preserved when exporting to *.woff2

**Comment by jwvanderbeck** [comment]
What about using these outside of a web context? For example I want to use it in a game using Unity where there is no option for enabling such advanced font features as more font heavy programs would have.

**Comment by alerque** [comment]
@jwvanderbeck First of all, please complaint to Unity. It's bad enough that as recently as a few years ago (as shown in comments above) browsers were still catching up. It's unacceptable that desktop software that draws text wouldn't give you access to this. It isn't "advanced" features — we're not even talking about variable fonts here, this is a pretty basic selector.

After you've complained to Unity I suggest you use one of many tools that are available to take an OTF font and generate another OTF with whatever features you want enabled or disabled by default and spoon feed that to you app. This is the standard way of getting modern font features into legacy apps.

**Comment by alerque** [comment]
By the way I'm leaving this open because it's something I'll look into when generating this font with Fontship ... the potential number of feature combinations that could be generated for legacy usages is quite large, but if we're automating it... at the very least maybe we'll have a command to generate your own font instances. Note as mentioned above you can already do this with other tools...

**Comment by alerque** [comment]
Here is a sample showing old-style and lining numbers from the [4.100 release](https://github.com/theleagueof/raleway/releases/tag/4.100).

<details><summary>SILE test code</summary>
<p>

```sile
\begin{document}
\script[src=packages/grid]
\font[family=Raleway,size=40pt]
\grid[spacing=1ex]
\grid:debug
\font[features=+onum]{Raleway +onum 0123458789}

\font[features=+lnum]{Raleway +lnum 0123458789}
\end{document}
```

</p></details>

![image](https://user-images.githubusercontent.com/173595/91447067-eb569780-e880-11ea-9192-8f16457da4ee.png)

Google Fonts does not support OpenType feature selection through their API at all. As published from this repository webfont builds are included. If you host them yourself you'll be able to use OT features as desired.

Also track [this issue](https://github.com/theleagueof/fontship/issues/76) for what will be the easiest way to generate your own instances. There is other tooling out there to take existing fonts and toggle the features, so feel free to go that route too but the official way supported by this project will be generating your own font instances from source using that feature (when it is added to Fontship). Subscribe to that issue if this interests you.
